name: Deploy Infra for Mongo on ECS

on:
  workflow_dispatch:

jobs:
  run_terraform_plan_apply:
    name: Run Terraform Plan & Apply
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Init
      id: init
      run: |
        cd mongo-ecs/infrastructure
        terraform init -input=false
    - name: Terraform Plan
      id: plan
      run: |
        cd mongo-ecs/infrastructure
        terraform plan -no-color -input=false
      continue-on-error: true
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1
    - name: Terraform Apply
      run: |
        cd mongo-ecs/infrastructure
        terraform apply --auto-approve -input=false